# Generated by Django 4.2.7 on 2023-12-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Company',
            new_name='name',
        ),
    ]
